all: 1.exe 2.exe 3.exe 4.exe 5.exe 6.exe 7.exe 8.exe 9.exe
1.exe: 1.c
	gcc 1.c -o 1.exe
2.exe: 2.c
	gcc 2.c -o 2.exe
3.exe: 3.c
	gcc 3.c -o 3.exe
4.exe: 4.c
	gcc 4.c -o 4.exe
5.exe: 5.c
	gcc 5.c -o 5.exe
6.exe: 6.c
	gcc 6.c -o 6.exe
7.exe: 7.c
	gcc 7.c -o 7.exe
8.exe: 8.c
	gcc 8.c -o 8.exe
9.exe: 9.c
	gcc 9.c -o 9.exe
