3.out: zadanie3.cpp
	g++ zadanie3.cpp -o 3.out
4.out: zadanie4.cpp
	g++ zadanie4.cpp -o 4.out
5.out: zadanie5.cpp
	g++ zadanie5.cpp -o 5.out
6.out: zadanie6.cpp
	g++ zadanie6.cpp -o 6.out
7.out: zadanie7.cpp
	g++ zadanie7.cpp -o 7.out
