all: lista.exe stos.exe bubble.exe kolejka.exe drzewo.exe
lista.exe: listajk.c
	gcc listajk.c -o lista.exe
stos.exe: stos.c
	gcc stos.c -o stos.exe
bubble.exe: bubble.c
	gcc bubble.c -o bubble.exe
kolejka.exe: kolejka.c
	gcc kolejka.c -o kolejka.exe
drzewo.exe: drzewo.c
	gcc drzewo.c -o drzewo.exe
