all: zad1.out zad2.out zad3.out zad4.out zad5.out
zad1.out: 1.cpp
	g++ 1.cpp -o zad1.out -std=c++11
zad2.out: 2.cpp
	g++ 2.cpp -o zad2.out -std=c++11

zad4.out: 4.cpp
	g++ 4.cpp -o zad4.out -std=c++11
zad5.out: 5.cpp
	g++ 5.cpp -o zad5.out -std=c++11
