all: lista.exe stos.exe bubble.exe kolejka.exe drzewo.exe merge.exe
lista.exe: lista.c
	gcc lista.c -o lista.exe
stos.exe: stos.c
	gcc stos.c -o stos.exe
bubble.exe: bubble.c
	gcc bubble.c -o bubble.exe
kolejka.exe: kolejka.c
	gcc kolejka.c -o kolejka.exe
drzewo.exe: drzewo.c
	gcc drzewo.c -o drzewo.exe
merge.exe: merge.c
	gcc merge.c -o merge.exe
